controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

app_index_inicio:
    path: /
    controller: App\Controller\Controller::inicio

app_index_crearcuenta:
    path: /index
    controller: App\Controller\Controller::index